### PR TITLE
Fix name of product_saleschannel table

### PR DESCRIPTION
**Pull request by rodolfobandeira**

### CODE REVIEW

**Comment by 24198** [comment]
Hi @rodolfobandeira! 

Thanks for your PR, I'll try to evaluate and merge it as soon as possible.

Kind Regards,

Jaimy Casteleijn

**Comment by 24198** [comment]
Hi @rodolfobandeira!

Unfortunately we can't merge the PR for now. At the moment it is breaking the installer since not all references to the table have been updated. Could you please update all references of 'product_saleschannel' to 'marello_product_saleschannel'. The code below shows the not updated reference in the foreign key creation. Thanks!

```
    /**
     * Add product_saleschannel foreign keys.
     *
     * @param Schema $schema
     */
    protected function addProductSaleschannelForeignKeys(Schema $schema)
    {
        $table = $schema->getTable('product_saleschannel');
        $table->addForeignKeyConstraint(
            $schema->getTable('marello_sales_sales_channel'),
            ['saleschannel_id'],
            ['id'],
            ['onDelete' => 'CASCADE', 'onUpdate' => null]
        );
        $table->addForeignKeyConstraint(
            $schema->getTable('marello_product_product'),
            ['product_id'],
            ['id'],
            ['onDelete' => 'CASCADE', 'onUpdate' => null]
        );
    }
```

**Comment by rodolfobandeira** [comment]
Hi @24198 

Sorry about that! Now it's fixed! Thanks!

**Comment by 24198** [comment]
Hi @rodolfobandeira 

Thank you for your contribution. Your PR has been successfully merged!

**Pull request merged**
