### PR TITLE
make supplier entity extendable

### PR DESCRIPTION
**Pull request by Janvdv**
Make supplier entity extendable

### CODE REVIEW

**Comment by 24198** [comment]
Hi @janvdv96,

Thanks for your contribution, we will look at it shortly!

Kind Regards,

Jaimy

**Comment by 24198** [comment]
Hi @janvdv96,

We've been looking at the contribution and in general it all looks OK. However we did find some additions we would like to see before merging this PR. Currently only adding the code to extend the Supplier is not enough, we would like to see the additions that the Supplier can be updated with fields that have been added to the entity. These additions are mainly in the create/update and view pages of the Supplier. 

If you can add these additions, that would be great.

Kind Regards,

Jaimy

**Comment by Janvdv** [comment]
Hi @24198

I've updated the PR with the requested changes. Let me know if this are all the changes you required.

**Comment by 24198** [comment]
Hi @janvdv96,

We've made a few minor tweaks, but the gist of the views is good! Thanks!
We're currently in the process of merging the changes. Thanks again for your contribution.

Kind Regards,

Jaimy

**Pull request merged**
