### PR TITLE
Code formatting in LoadDashboardData

### PR DESCRIPTION
**Pull request by umpirsky**

### CODE REVIEW

**Comment by 24198** [comment]
Hi umpirsky!

Thanks for the contribution, I'll see if I can handle and review it today! :)

**Comment by umpirsky** [comment]
@24198 Please hurry up, it is a very urgent fix. :trollface:

**Comment by 24198** [comment]
Thanks @umpirsky for the contribution! :)

**Comment by umpirsky** [comment]
Thanks for merging it, hope to push more in the future. :+1:

**Pull request merged**
